import {
  buildGuideMarkdown,
  deploymentJsonc,
  gatekeeperScaffold,
  slug,
  systemById,
  type ClientRecord,
} from "@cfos-practice/core";

export interface GeneratedFile {
  /** Path relative to the output root. */
  path: string;
  content: string;
}

function skillSeed(c: ClientRecord, name: string, dept: string, risk: string, systems: string[]): string {
  const sys = systems.map((id) => systemById(id)?.label ?? id).join(", ") || "none yet";
  return `# Skill: ${name}

**Client:** ${c.name} · **Dept:** ${dept} · **Risk tier:** ${risk} · **Systems:** ${sys}

## When to use
<!-- One sentence: the situation in the client's own vocabulary that triggers this workflow. -->

## Procedure
<!-- Numbered steps in the client's terms. Deterministic parts first; judgment calls marked. -->
1. TODO — captured from the champion during Phase 4 (knowledge curation).

## Approvals
${risk === "A" ? "Read-only — no approval required." : `Side effects queue for approval (see the policy matrix; approvers: payments → ${c.approvers.payments || "TBD"}, sends → ${c.approvers.sends || "TBD"}, records → ${c.approvers.records || "TBD"}).`}

## Sources of truth
<!-- Which system/document wins when data disagrees. -->
`;
}

/**
 * Generate the starter-repo seed files for a client record. Pure — returns
 * file descriptors; the CLI is responsible for writing them to disk.
 */
export function generateFiles(c: ClientRecord): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  files.push({ path: "deployment.jsonc", content: deploymentJsonc(c) + "\n" });
  files.push({ path: "SETUP.md", content: buildGuideMarkdown(c) });

  const custom = c.systems
    .map((id) => systemById(id))
    .filter((s): s is NonNullable<typeof s> => !!s && s.kind === "custom");
  for (const s of custom) {
    const approver =
      s.id === "qbo" || s.id === "stripe" || s.id === "square"
        ? c.approvers.payments || "APPROVER"
        : c.approvers.sends || "APPROVER";
    files.push({
      path: `packages/custom-gatekeeper/src/${s.id}.ts`,
      content: gatekeeperScaffold(s.id, approver) + "\n",
    });
  }

  const pilots = c.useCases.filter((u) => u.pilot);
  const seeds = pilots.length ? pilots : c.useCases.slice(0, 5);
  for (const u of seeds) {
    files.push({
      path: `skills/${slug(u.name)}.md`,
      content: skillSeed(c, u.name, u.dept, u.risk, u.systems),
    });
  }

  files.push({
    path: "README.md",
    content: `# ${c.name} — Cloudflare OS deployment seed

Generated by \`@cfos-practice/scaffold\` from the Studio engagement record.

- \`SETUP.md\` — the full ordered setup guide with acceptance checks
- \`deployment.jsonc\` — values for the cloudflare-os-starter template (reconcile key names against the pinned release you clone)
- \`packages/custom-gatekeeper/src/\` — gatekeeper scaffolds for the ${custom.length} custom system(s); align each class with the gatekeeper interface in the pinned release before shipping
- \`skills/\` — skill seeds for the pilot workflows, to be completed with the client's champion in Phase 4

These files are a **seed to copy into a fresh clone of** [cloudflare/cloudflare-os-starter](https://github.com/cloudflare/cloudflare-os-starter) — not a standalone project.
`,
  });

  return files;
}
